#!/bin/bash
set -e

: "${POSTGRES_DEMO_USER:="demo"}"
: "${POSTGRES_DEMO_DB:="demo"}"
: "${POSTGRES_DEMO_PASSWORD:="zerodaycloud1!"}"

psql -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE USER $POSTGRES_DEMO_USER WITH PASSWORD '$POSTGRES_DEMO_PASSWORD';

    CREATE DATABASE $POSTGRES_DEMO_DB;

    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DEMO_DB TO $POSTGRES_DEMO_USER;
EOSQL