version: '3.8'

networks:
  monitoring-net:
    driver: bridge

services:
  webapp:
    build: .
    container_name: webapp_server
    ports:
      - "5000:5000"
    networks:
      - monitoring-net
    restart: unless-stopped

  # Prometheus Service: The monitoring and alerting server
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_server
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring-net
    depends_on:
      - webapp
    restart: unless-stopped


